### ISSUE TITLE
UPDATED : Proofread, Grammar and General Feedback

### ISSUE THREAD

**Issue by DeastinY** [DeastinY/image_processing#1]
Since this is my first paper :tada: , I'd love any of the features mentioned above.
Will gladly accept any fixes for typos or grammar and offer some :heart: for feedback !

**Comment by rowmatrix** [comment]
I'll proofread it

**Comment by rowmatrix** [comment]
PR #3

**Comment by DeastinY** [comment]
thank you :heart:
